# TCL File Generated by Component Editor 23.1
# Sun Oct 13 07:21:31 GMT 2024
# DO NOT MODIFY


# 
# hsv_core "HSCALE-V CPU core" v1.0
#  2024.10.13.07:21:31
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module hsv_core
# 
set_module_property DESCRIPTION ""
set_module_property NAME hsv_core
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "HSCALE-V CPU core"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL hsv_core_top_flat
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false


# 
# parameters
# 
add_parameter HART_ID INTEGER 0 ""
set_parameter_property HART_ID DEFAULT_VALUE 0
set_parameter_property HART_ID DISPLAY_NAME "RISC-V hart ID"
set_parameter_property HART_ID WIDTH ""
set_parameter_property HART_ID TYPE INTEGER
set_parameter_property HART_ID UNITS None
set_parameter_property HART_ID ALLOWED_RANGES 0:255
set_parameter_property HART_ID DESCRIPTION ""
set_parameter_property HART_ID AFFECTS_GENERATION false
add_parameter FETCH_BURST_LEN INTEGER 4 ""
set_parameter_property FETCH_BURST_LEN DEFAULT_VALUE 4
set_parameter_property FETCH_BURST_LEN DISPLAY_NAME "Number of word beats per instruction fetch burst"
set_parameter_property FETCH_BURST_LEN WIDTH ""
set_parameter_property FETCH_BURST_LEN TYPE INTEGER
set_parameter_property FETCH_BURST_LEN UNITS None
set_parameter_property FETCH_BURST_LEN ALLOWED_RANGES 1:16
set_parameter_property FETCH_BURST_LEN DESCRIPTION ""
set_parameter_property FETCH_BURST_LEN AFFECTS_GENERATION false


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk_core clk Input 1


# 
# connection point rst
# 
add_interface rst reset end
set_interface_property rst associatedClock clk
set_interface_property rst synchronousEdges DEASSERT
set_interface_property rst ENABLED true
set_interface_property rst EXPORT_OF ""
set_interface_property rst PORT_NAME_MAP ""
set_interface_property rst CMSIS_SVD_VARIABLES ""
set_interface_property rst SVD_ADDRESS_GROUP ""

add_interface_port rst rst_core_n reset_n Input 1


# 
# connection point irq
# 
add_interface irq interrupt start
set_interface_property irq associatedAddressablePoint ""
set_interface_property irq associatedClock clk
set_interface_property irq associatedReset rst
set_interface_property irq irqScheme INDIVIDUAL_REQUESTS
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq irq_core irq Input 1


# 
# connection point imem
# 
add_interface imem axi4 start
set_interface_property imem associatedClock clk
set_interface_property imem associatedReset rst
set_interface_property imem readIssuingCapability 1
set_interface_property imem writeIssuingCapability 1
set_interface_property imem combinedIssuingCapability 1
set_interface_property imem ENABLED true
set_interface_property imem EXPORT_OF ""
set_interface_property imem PORT_NAME_MAP ""
set_interface_property imem CMSIS_SVD_VARIABLES ""
set_interface_property imem SVD_ADDRESS_GROUP ""

add_interface_port imem imem_araddr araddr Output 32
add_interface_port imem imem_arburst arburst Output 2
add_interface_port imem imem_arid arid Output 8
add_interface_port imem imem_arlen arlen Output 8
add_interface_port imem imem_arready arready Input 1
add_interface_port imem imem_arsize arsize Output 3
add_interface_port imem imem_arvalid arvalid Output 1
add_interface_port imem imem_rdata rdata Input 32
add_interface_port imem imem_rlast rlast Input 1
add_interface_port imem imem_rid rid Input 8
add_interface_port imem imem_rready rready Output 1
add_interface_port imem imem_rresp rresp Input 2
add_interface_port imem imem_rvalid rvalid Input 1
add_interface_port imem imem_awaddr awaddr Output 32
add_interface_port imem imem_awlen awlen Output 8
add_interface_port imem imem_awid awid Output 8
add_interface_port imem imem_awburst awburst Output 2
add_interface_port imem imem_awready awready Input 1
add_interface_port imem imem_awvalid awvalid Output 1
add_interface_port imem imem_awsize awsize Output 3
add_interface_port imem imem_bid bid Input 8
add_interface_port imem imem_bready bready Output 1
add_interface_port imem imem_bvalid bvalid Input 1
add_interface_port imem imem_wdata wdata Output 32
add_interface_port imem imem_wlast wlast Output 1
add_interface_port imem imem_wready wready Input 1
add_interface_port imem imem_wstrb wstrb Output 4
add_interface_port imem imem_wvalid wvalid Output 1
add_interface_port imem imem_arprot arprot Output 3
add_interface_port imem imem_awprot awprot Output 3


# 
# connection point dmem
# 
add_interface dmem axi4 start
set_interface_property dmem associatedClock clk
set_interface_property dmem associatedReset rst
set_interface_property dmem readIssuingCapability 1
set_interface_property dmem writeIssuingCapability 1
set_interface_property dmem combinedIssuingCapability 1
set_interface_property dmem ENABLED true
set_interface_property dmem EXPORT_OF ""
set_interface_property dmem PORT_NAME_MAP ""
set_interface_property dmem CMSIS_SVD_VARIABLES ""
set_interface_property dmem SVD_ADDRESS_GROUP ""

add_interface_port dmem dmem_araddr araddr Output 32
add_interface_port dmem dmem_arburst arburst Output 2
add_interface_port dmem dmem_arid arid Output 8
add_interface_port dmem dmem_arlen arlen Output 8
add_interface_port dmem dmem_arprot arprot Output 3
add_interface_port dmem dmem_arready arready Input 1
add_interface_port dmem dmem_arsize arsize Output 3
add_interface_port dmem dmem_arvalid arvalid Output 1
add_interface_port dmem dmem_awaddr awaddr Output 32
add_interface_port dmem dmem_awburst awburst Output 2
add_interface_port dmem dmem_awid awid Output 8
add_interface_port dmem dmem_awlen awlen Output 8
add_interface_port dmem dmem_awprot awprot Output 3
add_interface_port dmem dmem_awready awready Input 1
add_interface_port dmem dmem_awsize awsize Output 3
add_interface_port dmem dmem_awvalid awvalid Output 1
add_interface_port dmem dmem_bid bid Input 8
add_interface_port dmem dmem_bready bready Output 1
add_interface_port dmem dmem_bresp bresp Input 2
add_interface_port dmem dmem_bvalid bvalid Input 1
add_interface_port dmem dmem_rdata rdata Input 32
add_interface_port dmem dmem_rid rid Input 8
add_interface_port dmem dmem_rlast rlast Input 1
add_interface_port dmem dmem_rready rready Output 1
add_interface_port dmem dmem_rresp rresp Input 2
add_interface_port dmem dmem_rvalid rvalid Input 1
add_interface_port dmem dmem_wdata wdata Output 32
add_interface_port dmem dmem_wlast wlast Output 1
add_interface_port dmem dmem_wstrb wstrb Output 4
add_interface_port dmem dmem_wready wready Input 1
add_interface_port dmem dmem_wvalid wvalid Output 1

